name             'chef-server-bootstrap'
maintainer       'YOUR_NAME'
maintainer_email 'YOUR_EMAIL'
license          'All rights reserved'
description      'Installs/Configures leaf-deploy-chef_server'
long_description 'Installs/Configures leaf-deploy-chef_server'
version          '0.1.0'

depends           'user',                       '~> 0.3.0'
depends           'sudo',                       '~> 2.7.1'
depends           'logrotate',                  '~> 1.8.0'
depends           'cron',                       '~> 1.6.1'